runtime: python311

env_variables:
  PYTHONPATH: /opt/python/app

entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto