runtime: python311

env_variables:
  PYTHONPATH: /opt/python/app
  PLAYWRIGHT_BROWSERS_PATH: /opt/render/project/.cache/ms-playwright

entrypoint: bash start_server.sh

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto