name: Manual Paper Scraping

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      cloud_url:
        description: 'Cloud database URL'
        required: false
        default: 'https://research-tracker-466018.uc.r.appspot.com'
        type: string

jobs:
  scrape-and-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scrape and sync script
      env:
        CLOUD_URL: ${{ github.event.inputs.cloud_url }}
      run: |
        python scripts/scrape_and_sync.py
        
    - name: Upload results as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scrape-results
        path: |
          scraped_papers.json
          scrape_results.json
        retention-days: 7